services:
  main:
    image: kibble-main:latest
    container_name: kibble-main-container
    networks:
      kibble-sim-network:
        ipv4_address: 10.1.0.0
      lan-network:
        ipv4_address: 192.168.1.150
    build:
      context: ../
      dockerfile: ./simulator/main/Dockerfile
    depends_on:
      - database
    stop_grace_period: 1s  # infinite looping will not respond to SIGTERM
    extra_hosts:
      - "kibble-1:192.168.0.212"
      - "kibble-2:192.168.0.198"
      - "snmp-switch:192.168.0.239"
  daemon:
    image: kibble-daemon:latest
    networks:
      - kibble-sim-network
    build:
      context: ../
      dockerfile: ./simulator/daemon/Dockerfile
    stop_grace_period: 1s
  secondary:
    image: kibble-secondary:latest
    networks:
      - kibble-sim-network
    build:
      context: ./secondary
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN  # for traffic control
    stop_grace_period: 1s  # infinite looping will not respond to SIGTERM
  scpi:
    image: kibble-scpi-sim:latest
    networks:
      - kibble-sim-network
    build:
      context: ./scpi-simulator
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN  # for traffic control
    stop_grace_period: 1s  # gracefull shutdown doesn't matter
  database:
    image: mongodb/mongodb-community-server:8.2.3-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: kibble-mongodb
    ports:
      - "27017:27017" # allows connection to mongodb compass 
    networks:
      kibble-sim-network:
        ipv4_address: 10.1.0.2
        aliases:
          - database.internal
    volumes:
      - type: bind
        source: ./db
        target: /data/db
    stop_grace_period: 1s  # takes way too long without it

networks:
  kibble-sim-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8
          ip_range: 10.128.0.0/9
  lan-network:
    driver: macvlan
    driver_opts:
      parent: wlp39s0  # NOTE: change this to the interface that your SNMP switch is connected to using `ip addr`
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.128/25
