# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\"r\n\x0eStatusResponse\x12\x31\n\ttelemetry\x18\x01 \x03(\x0b\x32\x1e.StatusResponse.TelemetryEntry\x1a-\n\x0eTelemetryEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSRESPONSE._serialized_start=18
  _STATUSRESPONSE._serialized_end=132
  _STATUSRESPONSE_TELEMETRYENTRY._serialized_start=87
  _STATUSRESPONSE_TELEMETRYENTRY._serialized_end=132
# @@protoc_insertion_point(module_scope)
